; Generated by Auto-GUI 3.0.1
#SingleInstance Force
#NoEnv
SetWorkingDir %A_ScriptDir%
SetBatchLines -1

Menu Tray, Icon, shell32.dll, 16

Gui Font, s9, Segoe UI
Gui Add, Button, ginstall x10 y10 w80 h23, &Install
Gui Add, Button, ganova x10 y40 w80 h23, &Run ANOVA
Gui Add, Button, gpre x10 y70 w80 h30, &Run Preprocessing
Gui Add, Button, gPCA x10 y110 w80 h23, &Run PCA

Gui Show, w120 h141, Window
Return

install:
run %A_ScriptDir%\install.bat
Return

anova:
run %A_ScriptDir%\run_ANOVA.bat
Return

pre:
run %A_ScriptDir%\run_preprocessing.bat
Return

PCA:
run %A_ScriptDir%\run_PCA.bat
Return

GuiEscape:
GuiClose:
    ExitApp
